### ISSUE TITLE
ValueError: Cannot feed value of shape (42, 250, 250, 3) for Tensor 'images:0', which has shape '(?, 160, 160, 3)'

### ISSUE THREAD

**Issue by 1070148808** [ppwwyyxx/Adversarial-Face-Attack#1]
按照教程配置了环境出现问题

```
Traceback (most recent call last):
  File "face_attack.py", line 216, in <module>
    victim = model.compute_victim(args.data, args.target)
  File "face_attack.py", line 44, in compute_victim
    embeddings = self.eval_embeddings(image_batch)
  File "face_attack.py", line 118, in eval_embeddings
    return self.sess.run(self.embeddings, feed_dict={self.image_batch: batch_arr})
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1116, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (42, 250, 250, 3) for Tensor 'images:0', which has shape '(?, 160, 160, 3)'
```

请问怎么处理

**Comment by ppwwyyxx** [comment]
If you have followed the readme correctly, `/path/to/lfw_mtcnnpy_160` should only contain images of size 160x160. Your images, however, has shape of 250x250.
